### ISSUE TITLE
[BUG] Too many students mean self-defined students cannot be easily chosen.

### ISSUE THREAD

**Issue by WPettersson** [pkitazos/allocation-app#171]
**Describe the bug**
If there are many students, the field for selecting students for a self-defined project isn't filterable as the filter box is off screen.

**To Reproduce**
1. Create instance with say 250 students
2. Create self defined project, and try to filter the listed students

**Expected behavior**
An entry box where students are filterable should be visible on screen.

**Comment by WPettersson** [comment]
Fixed in the branch issue171-many-students-self-defined-not-filterable

**Comment by pkitazos** [comment]
Merged in PR #187
