### ISSUE TITLE
[BUG] Cannot remove sub-group admin

### ISSUE THREAD

**Issue by WPettersson** [pkitazos/allocation-app#173]
**Describe the bug**
The removeAdmin function appears to be written to only remove group admins; there needs to be a corresponding removeSubGroupAdmin function. Currently the UI tries to use removeAdmin to remove a sub-group admin, but since removeAdmin assumes the sub-group is null (i.e., the admin is a group admin) this fails.

**To Reproduce**
1. Create instance
2. Create sub-group admin
3. Remove sub-group admin

**Expected behavior**
Sub-group admin is deleted

**Comment by pkitazos** [comment]
Fixed in PR #191
