### ISSUE TITLE
[BUG] Admins cannot also be supervisors

### ISSUE THREAD

**Issue by WPettersson** [pkitazos/allocation-app#174]
**Describe the bug**
Instance admins will often want to also be supervisors, so this needs to be allowed for.

**To Reproduce**
1. Create instance
2. Create admin
3. Make them also a supervisor

**Expected behavior**
Admin can also upload projects

**Comment by WPettersson** [comment]
There's a partial fix in the branch admins-can-submit-projects.

This has a few changes, and needs further testing.

The "UserInInstance.Role" field should just be either STUDENT or
SUPERVISOR. Instead of storing ADMIN there, use "AdminInSpace" table.

The api.user.adminLevel / adminLevelInGroup / adminLevelInSubGroup
procedures are now just protectedProcedure, not adminProcedure, so that
regular users can check if they are admins. This is needed because:

If someone has the SUPERVISOR role, but is an admin of some sort, they
are shown the admin panel and not the supervisor panel for instances.
This does mean that they don't see their task list or similar.

For these admins who are supervisors, we just manually add the "Create
project" / "My Projects" buttons for them depending on the stage.

Lastly, the lowest AdminLevel is now AdminLevel.NONE.

**Comment by jhebus** [comment]
From an ADMIN/SUPERVISOR user perspective, i would like to add self-defined and normal student projects. As of 20th August i don't see how to do this. Has the live instance been updated?

**Comment by pkitazos** [comment]
> From an ADMIN/SUPERVISOR user perspective, i would like to add self-defined and normal student projects. As of 20th August i don't see how to do this. Has the live instance been updated?

This is currently still being worked on, but it should be implemented and deployed to the live site in the next couple days. I will keep you updated
