### ISSUE TITLE
[BUG] Some people appear as supervisors in Project Submissions but not elsewhere

### ISSUE THREAD

**Issue by WPettersson** [pkitazos/allocation-app#199]
**Describe the bug**
Some people (in particular, me) appear in the list "Project Submissions" but do not have the ability to submit projects and don't appear in the "All Supervisors" list.

**To Reproduce**
1. Go to "Instance Home"
2. Click on "Project Submissions"
3. Search for William Pettersson
4. See me
5. Go to "All Supervisors"
6. Search for William Pettersson

**Expected behavior**
I feel like I should be listed there

I suspect this is due to some inconsistency in the database.

**Comment by pkitazos** [comment]
This seems to have been a residual bug from back when admins could not be supervisors. When adding your details to the instance, the `SupervisorInstanceDetails` row seems to have been created correctly, but your `UserInInstance` row still had your role set as ADMIN. I manually swapped your role over to Supervisor and you now appear in the "All Supervisors" page as well.
