### ISSUE TITLE
[FEATURE] Download information of shortlisting/preferences made per project as ADMIN

### ISSUE THREAD

**Issue by jhebus** [pkitazos/allocation-app#215]
**Is your feature request related to a problem? Please describe.**
I would like to understand, as an admin, what the distribution of project selection and shortlisting was from student for projects _after the deadline_ for selection. 

**Describe the solution you'd like**
Maybe a download of a csv?

**Describe alternatives you've considered**
Don't know 

**Additional context**

**Comment by pkitazos** [comment]
Would you just want aggregate values? Something like

| student ID | preferences count | shortlist count |
|---|---|---|
|123456A|10|25|
|1234567B|12|15|

or

| project ID | preferences count | shortlist count |
|---|---|---|
|0123|50|100|
|0124|9|24|

Or would it be more helpful if displayed in some other format?

**Comment by jhebus** [comment]
In general, i want to understand the spread of student project selections by project / topic / supervisor. The goal is working to understand how badly students are picking projects of certain types or from certain supervisors. 

My questions would be:
- how many students picked a particular project and with what ranking
- how many students picked a particular prof's project(s) and with what ranking
- what was the distribution of project selections by keyword and with what ranking

if you can put this in csv format, i can write a script to make graphs
